---
- name: Performing Tasks for CentOS
  include_tasks: redhat.yml
  when: ansible_facts['ansible_os_family'] == 'RedHat'

- name: Performing Tasks for Ubuntu
  include_tasks: debian.yml
  when: ansible_facts['ansible_os_family'] == 'Debian'
...