---
- name: Performing Tasks for CentOS
  include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'

- name: Performing Tasks for Ubuntu
  include_tasks: debian.yaml
  when: ansible_os_family == 'Debian'
...