---
- name: Ensure default directories in home
  file:
    path: '{{item}}'
    state: directory
    mode: '0700'
    owner: '{{host_user}}'
    group: '{{host_user}}'
  loop:
    - '/home/{{host_user}}/Documentos'
    - '/home/{{host_user}}/Documentos/Projetos'
    - '/home/{{host_user}}/Documentos/Projetos/ansible'
    - '/home/{{host_user}}/Documentos/Projetos/git'
    - '/home/{{host_user}}/Documentos/Projetos/terraform'
    - '/home/{{host_user}}/Documentos/Projetos/treinamentos'
    - '/home/{{host_user}}/Documentos/Projetos/docker'

- name: Create folder config
  ansible.builtin.file:
      path: /home/{{host_user}}/.config
      state: directory
      owner: '{{host_user}}'
      group: '{{host_user}}'
      mode: '0775'

- name: Get starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'

- name: Install starship
  ansible.builtin.shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh

- name: Copy starship config
  ansible.builtin.copy:
    src: starship.toml
    dest: /home/{{host_user}}/.config/starship.toml

- name: Copy bashrc
  ansible.builtin.copy:
    src: bashrcUbuntu
    dest: /home/{{host_user}}/.bashrc
    mode: '0644'
    owner: '{{host_user}}'
    group: '{{host_user}}'

- name: Copy zshrc
  ansible.builtin.copy:
    src: zshrcUbuntu
    dest: /home/{{host_user}}/.zshrc
    mode: '0644'
    owner: '{{host_user}}'
    group: '{{host_user}}'

- name: Install micro plugins
  ansible.builtin.command: '{{ item }}'
  loop:
    - 'micro -plugin install monokai-dark'
    - 'micro -plugin install gotham-colors'
    - 'micro -plugin install nordcolors'
...