---
- name: Setando hostname
  ansible.builtin.hostname:
    name: '{{hostname_set}}'

- name: Criando diretorios base
  file:
    path: '{{item}}'
    state: directory
    mode: '0700'
    owner: '{{host_user}}'
    group: '{{host_user}}'
  loop:
    - '/home/{{host_user}}/Documentos/Projetos'
    - '/home/{{host_user}}/Documentos/Projetos/ansible'
    - '/home/{{host_user}}/Documentos/Projetos/git'
    - '/home/{{host_user}}/Documentos/Projetos/terraform'
    - '/home/{{host_user}}/Documentos/Projetos/treinamentos'
    - '/home/{{host_user}}/Documentos/Projetos/vagrant'
    - '/home/{{host_user}}/Documentos/Projetos/docker'

- name: Baixando script starship
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'

- name: Instalando starship
  ansible.builtin.shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh

- name: Copiando configuracao starship
  ansible.builtin.copy:
    src: starship.toml
    dest: /home/{{host_user}}/.config/starship.toml

- name: Criando diretorio de temas Tilix
  ansible.builtin.file:
      path: /home/{{host_user}}/.config/tilix/schemes
      state: directory
      owner: '{{host_user}}'
      group: '{{host_user}}'
      mode: '0775'

- name: Clonando temas para o Tilix
  ansible.builtin.git:
    repo: https://codeberg.org/SnowCode/tilix-colors.git
    dest: /home/{{host_user}}/.config/tilix/schemes/

- name: Copiando tmux.conf
  ansible.builtin.copy:
    src: tmux.conf
    dest: /home/{{host_user}}/.tmux.conf
    mode: '0644'
    owner: '{{host_user}}'
    group: '{{host_user}}'

- name: Instalando micro plugins
  ansible.builtin.command: '{{ item }}'
  loop:
    - 'micro -plugin install monokai-dark'
    - 'micro -plugin install gotham-colors'
    - 'micro -plugin install nordcolors'

- name: Alvo base Redhat 
  include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'

- name: Alvo base Debian
  include_tasks: debian.yaml
  when: ansible_os_family == 'Debian'
...