---
- name: Get starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'

- name: Install starship
  ansible.builtin.shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh

- name: Copy starship config
  ansible.builtin.copy:
    src: starship.toml
    dest: /home/{{host_user}}/.config/starship.toml

- name: Copy bashrc
  ansible.builtin.copy:
    src: bashrcFedora
    dest: /home/{{host_user}}/.bashrc
    mode: '0644'
    owner: '{{host_user}}'
    group: '{{host_user}}'

- name: Copy zshrc
  ansible.builtin.copy:
    src: zshrcFedora
    dest: /home/{{host_user}}/.zshrc
    mode: '0644'
    owner: '{{host_user}}'
    group: '{{host_user}}'

- name: Create folder Tilix schemes
  ansible.builtin.file:
      path: /home/{{host_user}}/.config/tilix/schemes
      state: directory
      owner: '{{host_user}}'
      group: '{{host_user}}'
      mode: '0775'

- name: Clone repository scheme Tilix
  ansible.builtin.git:
    repo: https://codeberg.org/SnowCode/tilix-colors.git
    dest: /home/{{host_user}}/.config/tilix/schemes/

- name: Install micro plugins
  ansible.builtin.command: '{{ item }}'
  loop:
    - 'micro -plugin install monokai-dark'
    - 'micro -plugin install gotham-colors'
    - 'micro -plugin install nordcolors'
...