---
- name: Copiando bashrc
  ansible.builtin.copy:
    src: bashrcFedora
    dest: /home/{{host_user}}/.bashrc
    mode: '0644'
    owner: '{{host_user}}'
    group: '{{host_user}}'

- name: Copiando zshrc
  ansible.builtin.copy:
    src: zshrcFedora
    dest: /home/{{host_user}}/.zshrc
    mode: '0644'
    owner: '{{host_user}}'
    group: '{{host_user}}'
...