---
- name: Dotfiles bash/zsh distros base Debian
  block:
    - name: Copiando bashrc
      ansible.builtin.copy:
        src: bashrcUbuntu
        dest: /home/{{host_user}}/.bashrc
        mode: '0644'
        owner: '{{ host_user }}'
        group: '{{ host_user }}'

    - name: Copiando zshrc
      ansible.builtin.copy:
        src: zshrcUbuntu
        dest: /home/{{ host_user }}/.zshrc
        mode: '0644'
        owner: '{{ host_user }}'
        group: '{{ host_user }}'
  when: ansible_os_family == 'Debian'

- name: Dotfiles bash/zsh distros base RedHat
  block:
    - name: Copiando bashrc
      ansible.builtin.copy:
        src: bashrcFedora
        dest: /home/{{ host_user }}/.bashrc
        mode: '0644'
        owner: '{{ host_user }}'
        group: '{{ host_user }}'

    - name: Copiando zshrc
      ansible.builtin.copy:
        src: zshrcFedora
        dest: /home/{{ host_user }}/.zshrc
        mode: '0644'
        owner: '{{ host_user }}'
        group: '{{ host_user }}'
  when: ansible_os_family == 'RedHat'
...
