---
- name: Criando pasta fonts
  ansible.builtin.file:
      path: /home/{{host_user}}/.local/share/fonts
      state: directory
      owner: '{{host_user}}'
      group: '{{host_user}}'
      mode: '0775'

- name: Instalando NerdFonts
  ansible.builtin.unarchive:
    src: '{{item}}'
    dest: /home/{{host_user}}/.local/share/fonts
    remote_src: yes
  with_items: 
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/FiraCode.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/Hack.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/Inconsolata.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/Ubuntu.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/UbuntuMono.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/ProFont.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/Meslo.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/SourceCodePro.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/RobotoMono.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/JetBrainsMono.zip

- name: Refresh cache
  ansible.builtin.shell: fc-cache -vf

...
