---
- name: Criando pasta fonts
  ansible.builtin.file:
      path: /home/{{host_user}}/.local/share/fonts
      state: directory
      owner: '{{host_user}}'
      group: '{{host_user}}'
      mode: '0775'

- name: Instalando NerdFonts
  ansible.builtin.unarchive:
    src: '{{item}}'
    dest: /home/{{host_user}}/.local/share/fonts
    remote_src: yes
  with_items: 
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Inconsolata.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Ubuntu.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/UbuntuMono.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/ProFont.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Meslo.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/SourceCodePro.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/RobotoMono.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/JetBrainsMono.zip

- name: Refresh cache
  ansible.builtin.shell: fc-cache -vf

...
