- name: Create folder fonts
  file:
      path: /home/{{ansible_user_id}}/.local/share/fonts
      state: directory
      owner: '{{ansible_user_id}}'
      group: '{{ansible_user_id}}'
      mode: '0775'

- name: Installing FiraCode Font
  unarchive:
    src: 'https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip'
    dest: /home/{{ansible_user_id}}/.local/share/fonts
    remote_src: yes