---
- name: Create folder fonts
  ansible.builtin.file:
      path: /home/{{ansible_user_id}}/.local/share/fonts
      state: directory
      owner: '{{ansible_user_id}}'
      group: '{{ansible_user_id}}'
      mode: '0775'

- name: Installing NerdFonts
  ansible.builtin.unarchive:
    src: '{{item}}'
    dest: /home/{{ansible_user_id}}/.local/share/fonts
    remote_src: yes
  with_items: 
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Inconsolata.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Ubuntu.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/UbuntuMono.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/ProFont.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Meslo.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/SourceCodePro.zip
    - https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/RobotoMono.zip    

- name: Refresh font cache
  ansible.builtin.shell: fc-cache -vf

...