---
- name: Adicionando Repositorio Flathub
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        
- name: Instalando Apps via flatpak
  community.general.flatpak:
    name: 
      - com.spotify.Client
      - com.discordapp.Discord
      - com.mattjakeman.ExtensionManager
      - com.jgraph.drawio.desktop
      - md.obsidian.Obsidian
      - cc.arduino.IDE2
      - org.remmina.Remmina
      - com.anydesk.Anydesk
      - org.telegram.desktop
      - com.dropbox.Client
      - com.microsoft.Edge
      - com.github.unrud.VideoDownloader
      - com.github.IsmaelMartinez.teams_for_linux
      - io.podman_desktop.PodmanDesktop
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.videolan.VLC
    state: present
...