---
- name: Adicionando Repositorio Flathub
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        
- name: Instalando Apps via flatpak
  community.general.flatpak:
    name: 
      - cc.arduino.IDE2
      - com.agateau.PixelWheels
      - com.anydesk.Anydesk
      - com.discordapp.Discord
      - com.dropbox.Client
      - com.github.IsmaelMartinez.teams_for_linux
      - com.github.unrud.VideoDownloader
      - com.jgraph.drawio.desktop
      - com.ktechpit.wonderwall
      - com.mattjakeman.ExtensionManager
      - com.microsoft.Edge
      - com.raggesilver.BlackBox
      - com.spotify.Client
      - io.github.realmazharhussain.GdmSettings
      - io.gitlab.gregorni.Calligraphy
      - md.obsidian.Obsidian
      - org.gabmus.hydrapaper
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.gnome.Snapshot
      - org.gnome.Solanum
      - org.localsend.localsend_app
      - org.nickvision.money
      - org.remmina.Remmina
      - org.telegram.desktop
      - org.videolan.VLC
    state: present
...