---
- name: Adicionando chave Hashicorp
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.releases.hashicorp.com/gpg

- name: Adicionando Repositorio Hashicorp
  yum_repository:
    name: hashicorp-stable
    description: Hashicorp Softwares
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    state: present

- name: Instalando Terrafor/Packer/Vault
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
    loop:
      - terraform
      - packer
      - vault
...