---
- name: Helm distro base Debian
  block:
    - name: Adicionando chave Helm
      ansible.builtin.apt_key:
        url: 'https://baltocdn.com/helm/signing.asc'
        keyring: /etc/apt/keyrings/helm.gpg
        state: present
    - name: Adicionando Repositorio Helm
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main'
        state: present
        filename: helm
    - name: Instalando Helm
      ansible.builtin.apt:
        name: helm
  when: ansible_os_family == 'Debian'

- name: Helm distro base RedHat
  block:
    - name: Instalando Helm
      ansible.builtin.dnf:
        name: helm
        state: present
  when: ansible_os_family == 'RedHat'
...