---
- name: Instalando Kubectl
  ansible.builtin.dnf:
    name: kubernetes-client
    state: present
    
- name: Instalando Kubeadm
  ansible.builtin.dnf:
    name: kubernetes-kubeadm
    state: present
...