---
- name: Apps devops distro base Debian
  block:
    - name: Adicionando chave Microsoft
      ansible.builtin.apt_key:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        keyring: /usr/share/keyrings/packages.microsoft.gpg
        state: present

    - name: Adicionando Repositorio Microsoft
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main'    
        state: present
        filename: vscode
    
    - name: Instalando Visual Studio Code
      ansible.builtin.apt:
        name: code

    - name: Adicionando Repositorio Azure
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main'
        state: present
        filename: azure-cli

    - name: Instalando Azure Cli
      ansible.builtin.apt:
        name: azure-cli
  when: ansible_os_family == 'Debian'

- name: Apps devops distro base Redhat
  block:
    - name: Adicionando chave Microsoft
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Adicionando Repositorio Microsoft
      yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: yes
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Instalando Visual Studio Code
      ansible.builtin.dnf:
        name: code
        state: present
  when: ansible_os_family == 'RedHat'      
...