---
- name: Adicionando chave Microsoft
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Adicionando Repositorio Microsoft
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    state: present
    
- name: Instalando Visual Studio Code
  ansible.builtin.dnf:
    name: code
    state: present
...