---
- name: Instalando Virtualizador KVM/Qemu
  ansible.builtin.package:
    name: 
      - qemu-kvm
      - libvirt-daemon-system
      - virt-manager
      - virt-viewer    
      - ruby-libvirt
      - qemu
      - libvirt-daemon-system
      - libvirt-clients
      - ebtables
      - dnsmasq-base
      - libxslt-dev
      - libxml2-dev
      - libvirt-dev
      - zlib1g-dev
      - ruby-dev
      - libguestfs-tools
    state: present
...