---
- name: Install Virtualization
  ansible.builtin.package: name={{item}}
  loop:
    - qemu-kvm
    - libvirt-daemon-system
    - virt-manager
    - virt-viewer

- name: Adding existing user to group libvirt
  ansible.builtin.user: 
    name: '{{ ansible_user_id }}'
    groups: libvirt 
    append: yes
...