---
- name: Install virtualization Group
  ansible.builtin.dnf:
    name: '@virtualization'
    state: present

- name: Install libvirt
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop:
    - libvirt
    - libvirt-devel
    - libxml2-devel
    - ruby-devel
    - libguestfs-tools

- name: Configure libvirtd.conf - 1
  ansible.builtin.command: sed -i '/unix_sock_group/s/^# *//' /etc/libvirt/libvirtd.conf

- name: Configure libvirtd.conf - 2
  ansible.builtin.command: sed -i '/unix_sock_rw_perms/s/^# *//' /etc/libvirt/libvirtd.conf

- name: "Manage Virtualization Services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: "started"
    enabled: true
  become: true
  loop:
    - "virtqemud.service"
    - "virtnetworkd.service"
    - "libvirtd.service"

- name: Configure vagrant libvirt plugin
  ansible.builtin.command: vagrant plugin install vagrant-libvirt
...