---
- name: Instalando Grupo Virtualization
  ansible.builtin.dnf:
    name: '@virtualization'
    state: present

- name: Instalando libvirt
  ansible.builtin.dnf:
    name: 
      - libvirt
      - libvirt-devel
      - libxml2-devel
      - ruby-devel
      - libguestfs-tools
    state: present

- name: Configurando libvirtd.conf - 1
  ansible.builtin.command: sed -i '/unix_sock_group/s/^# *//' /etc/libvirt/libvirtd.conf

- name: Configurando libvirtd.conf - 2
  ansible.builtin.command: sed -i '/unix_sock_rw_perms/s/^# *//' /etc/libvirt/libvirtd.conf

- name: Ativando e Inicializando servicos
  ansible.builtin.service:
    name:
      - virtqemud.service
      - virtnetworkd.service
      - libvirtd.service
    state: started
    enabled: true    
...