---
- name: Virtualizador KVM/Qemu distro base Debian
  block:
    - name: Instalando Pacotes Virtualizacao
      ansible.builtin.package:
        name: 
          - qemu-kvm
          - libvirt-daemon-system
          - virt-manager
          - virt-viewer    
          - ruby-libvirt
          - libvirt-daemon-system
          - libvirt-clients
          - ebtables
          - dnsmasq-base
          - libxslt-dev
          - libxml2-dev
          - libvirt-dev
          - zlib1g-dev
          - ruby-dev
          - libguestfs-tools
        state: present
  when: ansible_os_family == 'Debian'

- name: Virtualizador KVM/Qemu distro base RedHat
  block:
    - name: Instalando Grupo Virtualization
      ansible.builtin.dnf:
        name: '@virtualization'
        state: present

    - name: Instalando libvirt
      ansible.builtin.dnf:
        name: 
          - libvirt
          - libvirt-devel
          - libxml2-devel
          - ruby-devel
          - libguestfs-tools
        state: present

    - name: Configurando libvirtd.conf - 1
      ansible.builtin.command: sed -i '/unix_sock_group/s/^# *//' /etc/libvirt/libvirtd.conf

    - name: Configurando libvirtd.conf - 2
      ansible.builtin.command: sed -i '/unix_sock_rw_perms/s/^# *//' /etc/libvirt/libvirtd.conf

    - name: Ativando e Inicializando servicos
      ansible.builtin.service:
        name: '{{item}}'
        state: started
        enabled: true
      become: true
      loop:
        - virtqemud.service
        - virtnetworkd.service
        - libvirtd.service
  when: ansible_os_family == 'RedHat'
...
