---
- name: Adicionando chave Microsoft
  ansible.builtin.apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    keyring: /usr/share/keyrings/packages.microsoft.gpg
    state: present
- name: Adicionando Repositorio Microsoft
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main'    
    state: present
    filename: vscode
- name: Instalando Visual Studio Code
  ansible.builtin.apt:
    name: code

- name: Adicionando Repositorio Azure
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main'
    state: present
    filename: azure-cli
- name: Instalando Azure Cli
  ansible.builtin.apt:
    name: azure-cli

- name: Adicionando chave Hashicorp
  ansible.builtin.apt_key:
    url: 'https://apt.releases.hashicorp.com/gpg'
    keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    state: present
- name: Adicionando Repositorio Hashicorp
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
    state: present
    filename: hashicorp
- name: Instalando Terraform
  ansible.builtin.apt:
    name: terraform

- name: Instalando Packer
  ansible.builtin.apt:
    name: packer

- name: Instalando Vault
  ansible.builtin.apt:
    name: vault

- name: Adicionando chave Docker
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    keyring: /usr/share/keyrings/docker.gpg
    state: present
- name: Adicionando Repositorio Docker
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
    filename: docker
- name: Instalando Docker
  ansible.builtin.apt:
    package:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin      
- name: Adicionando usuario no grupo docker
  ansible.builtin.user: 
    name: '{{ host_user }}'
    groups: docker 
    append: yes

- name: Adicionando chave Kubernetes
  ansible.builtin.apt_key:
    url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    state: present

- name: Adicionando Repositorio Kubernetes
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    filename: kubernetes

- name: Instalando Kubectl
  ansible.builtin.apt:
    name: kubectl

- name: Instalando Kubeadm
  ansible.builtin.apt:
    name: kubeadm

- name: Adicionando chave Helm
  ansible.builtin.apt_key:
    url: 'https://baltocdn.com/helm/signing.asc'
    keyring: /etc/apt/keyrings/helm.gpg
    state: present
- name: Adicionando Repositorio Helm
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main'
    state: present
    filename: helm
- name: Instalando Helm
  ansible.builtin.apt:
    name: helm

- name: Instalando minikube
  ansible.builtin.apt:
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb

...