---
- name: Docker distro base Debian
  block:
    - name: Adicionando chave Docker
      ansible.builtin.apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        keyring: /usr/share/keyrings/docker.gpg
        state: present
    
    - name: Adicionando Repositorio Docker
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
        state: present
        filename: docker

    - name: Instalando Docker
      ansible.builtin.apt:
      package:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

    - name: Adicionando usuario no grupo docker
      ansible.builtin.user: 
        name: '{{ host_user }}'
        groups: docker 
        append: yes
  when: ansible_os_family == 'Debian'
...