---
- name: Performing Tasks for Redhat Like
  include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'

- name: Performing Tasks for Debian Like
  include_tasks: debian.yaml
  when: ansible_os_family == 'Debian'
...