---
- name: Adicionando chave Microsoft
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Adicionando Repositorio Microsoft
  yum_repository:
      name: vscode
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      enabled: yes
      gpgcheck: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      state: present

- name: Instalando Visual Studio Code
  ansible.builtin.dnf:
    name: code
    state: present

- name: Adicionando chave Hashicorp
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.releases.hashicorp.com/gpg

- name: Adicionando Repositorio Hashicorp
  yum_repository:
    name: hashicorp-stable
    description: Hashicorp Softwares
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    state: present

- name: Instalando Terrafor/Packer/Vault
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop:
    - terraform
    - packer
    - vault

- name: Instalando Kubectl
  ansible.builtin.dnf:
    name: kubernetes-client
    state: present

- name: Instalando Kubeadm
  ansible.builtin.dnf:
    name: kubernetes-kubeadm
    state: present

- name: Instalando miniKube
  ansible.builtin.dnf:
    name: '{{minikube_url}}'
    state: present
    disable_gpg_check: true

- name: Instalando Helm
  ansible.builtin.dnf:
    name: helm
    state: present

- name: Instalando Grupo Development
  ansible.builtin.dnf:
    name: '@development-tools'
    state: present
...