---
## Link download minikube
## https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm - Fedora
## https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb  - Ubuntu
minikube_url:
...