---
- hosts: localhost
  become: true
  tasks:
  - name: update and upgrade Debian
    apt: 
      name: '*'
      state: latest        
      update_cache: yes
      only_upgrade: yes
    when: ansible_os_family == 'Debian'

  - name: upgrade all packages Centos
    yum: 
      name: '*' 
      state: latest
      update_cache: yes
      update_only: yes
    when: ansible_os_family == 'RedHat'

  - name: Install packages
    package: name={{item}}
    with_items:
      - htop
      - iotop
      - iftop
      - hdparm
      - locate
      - traceroute
      - tree
      - ipcalc
      - sipcalc
      - whois
      - dnsutils
      - net-tools
      - ncdu
      - neofetch
      - bash-completion
      - fzf
      - curl
      - grc
      - nmap
      - links
      - tcpdump
      - ethtool
      - iptraf-ng
      - micro
      - qbittorrent
      - sed
      - bpytop
      - exa
      - ansible 
      - python3-pip
      - golang
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - gnome-tweaks

  - name: Enable Flathub Repositorio
    command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - name: Install Flatpak App
    command: flatpak install --assumeyes name={{item}}
    with_items:
      - com.discordapp.Discord
      - com.mattjakeman.ExtensionManager
      - com.jgraph.drawio.desktop
      - md.obsidian.Obsidian
      - cc.arduino.IDE2
      - org.remmina.Remmina
      - com.anydesk.Anydesk
