- hosts: localhost
  become: true
  tasks:
  - name: update and upgrade Debian
      apt: upgrade=yes update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'

  - name: upgrade all packages Centos
      yum: name=* state=latest
      when: ansible_os_family == 'RedHat'

  - name: Install packages
  package: name={{item}}
  with_items:
    - htop
    - iotop
    - iftop
    - hdparm
    - locate
    - traceroute
    - tree
    - ipcalc
    - sipcalc
    - whois
    - dnsutils
    - net-tools
    - ncdu
    - neofetch
    - bash-completion
    - fzf
    - curl
    - grc
    - nmap
    - links
    - tcpdump
    - ethtool
    - iptraf-ng
    - micro
    - qbittorrent
    - sed
    - bpytop
    - exa
    - ansible 
    - python3-pip
    - golang
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting