# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/servers.pub").first.strip
  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
  config.vm.synced_folder ".", "/vagrant", type: 'rsync', disabled: true, nfs: false, nfs_prune: false, server_setup: false
  config.vm.box = "debian/bookworm64"
  

  config.vm.define :front do |front|  
  
    front.vm.hostname = "zabbix-front"    
    front.vm.network "public_network", :dev => "br0", :mode => "bridge", :type => "bridge",	:ip => "ipdoserver"
    
    front.vm.provider :libvirt do |zbxfront|
      zbxfront.default_prefix = "zbx-"
      zbxfront.cpus = 2
      zbxfront.memory = 2048
      zbxfront.memorybacking :access, :mode => "shared"
    end
  end

  config.vm.define :server do |server|  
  
    server.vm.hostname = "zabbix-server"    
    server.vm.network "public_network", :dev => "br0", :mode => "bridge", :type => "bridge",	:ip => "ipdoserver"
    
    server.vm.provider :libvirt do |zbxserver|
      zbxserver.default_prefix = "zbx-"
      zbxserver.cpus = 2
      zbxserver.memory = 2048
      zbxserver.memorybacking :access, :mode => "shared"
    end
  end

  config.vm.define :db do |db|  
  
    db.vm.hostname = "zabbix-db"    
    db.vm.network "public_network", :dev => "br0", :mode => "bridge", :type => "bridge",	:ip => "ipdoserver"
    
    db.vm.provider :libvirt do |zbxdb|
      zbxdb.default_prefix = "zbx-"
      zbxdb.cpus = 4
      zbxdb.memory = 6144
      zbxdb.memorybacking :access, :mode => "shared"
    end
  end 
end
